### ISSUE TITLE
Solr fails to start on localhost

### ISSUE THREAD

**Issue by harsham05** [jiezhou0731/DynamicSearchEngine#1]
Hi @jiezhou0731 ,

After successful build, I am unable to start Solr locally. 
 
harsha@ubuntu:~/Documents/CS572DR/DynamicSearchEngine/solr/bin$ **./solr start**

Waiting to see Solr listening on port 8081 [/]  Still not seeing Solr listening on 8081 after 30 seconds!
tail: cannot open ‘/home/harsha/Documents/CS572DR/DynamicSearchEngine/solr/server/logs/solr.log’ for reading: No such file or directory

**Thank you in advance,
Harsha**

**Comment by harsham05** [comment]
The below patch is for Solr 4.10 but Dynamic Search Engine uses Solr 5
***https://issues.apache.org/jira/browse/SOLR-6646***

**Comment by lewismc** [comment]
@harsham05 

> harsha@ubuntu:~/Documents/CS572DR/DynamicSearchEngine/solr/bin$ ./solr start

I don't see this mentioned anywhere in the README for this project! Can you please trying following the README then check back here?

**Comment by harsham05** [comment]
Hi @lewismc , Trying **./solr_org** gives me usage instructions for **./solr start -p <port-no>**

harsha@ubuntu:~/Documents/CS572DR/DynamicSearchEngine$ **solr/bin/./solr_org**

Usage: solr COMMAND OPTIONS
       where COMMAND is one of: start, stop, restart, status, healthcheck, create, create_core, create_collection, delete

  Standalone server example (start Solr running in the background on port 8984):

    ./solr start -p 8984

  SolrCloud example (start Solr running in SolrCloud mode using localhost:2181 to connect to ZooKeeper, with 1g max heap size and remote Java debug options enabled):

    ./solr start -c -m 1g -z localhost:2181 -a "-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=1044"

Pass -help after any COMMAND to see command-specific usage information,
  such as:    ./solr start -help or ./solr stop -help

**Comment by chrismattmann** [comment]
@harsham05 @jiezhou0731 @lewismc can we get a reply to Harsha's question here?

**Comment by harsham05** [comment]
@chrismattmann @lewismc @jiezhou0731 
Hi Prof. Mattmann & All, I am still testing out Georgetown's reRank REST api for fields besides "content". I will look into this issue later.

**Comment by lewismc** [comment]
OK so I can confirm that this is not a bug as I cannot reproduce it.
Please see attached screenshots for building from source
<img width="1440" alt="screen shot 2015-10-26 at 8 27 16 pm" src="https://cloud.githubusercontent.com/assets/1165719/10748677/ccce6d7e-7c1f-11e5-900d-1830e5704b36.png">
and then navigating to the Solr server
<img width="1440" alt="screen shot 2015-10-26 at 8 28 05 pm" src="https://cloud.githubusercontent.com/assets/1165719/10748684/deaeae3c-7c1f-11e5-9247-c560b5965dd7.png">

**Comment by harsham05** [comment]
@lewismc  Thank you Lewis!

**Comment by lewismc** [comment]
Please also see the recent pull request I sent to the project, you require not only a JDK 1.8 but also javac 1.8 defined.

**Comment by harsham05** [comment]
@lewismc Yes, I switch b/w Java 7 & 8

```
harsha@ubuntu:~/Documents/CS572DR/DynamicSearchEngine/solr/bin$ java -version
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)
harsha@ubuntu:~/Documents/CS572DR/DynamicSearchEngine/solr/bin$ 
harsha@ubuntu:~/Documents/CS572DR/DynamicSearchEngine/solr/bin$ 
harsha@ubuntu:~/Documents/CS572DR/DynamicSearchEngine/solr/bin$ javac -version
javac 1.8.0_60
```

**Comment by ngarafol** [comment]
+1
